### ISSUE TITLE
Diagramme UML : classe

### ISSUE THREAD

**Issue by droumanet** [MKertane/Asimov-PHP#1]
Bonne idée que de mettre un PNG directement dans le readme.MD 😉

Points à corriger : 
- une note doit avoir au moins une matière (note ----- 1 Matière)
- il vaut mieux relier professeur à classe, plutôt qu'à Eleve
- partout où il y a x..* ------- x..* il faut créer une table associative (voir support de cours UML)
- La table proviseur est inutile, car il ne peut y avoir qu'un seul proviseur dans l'établissement (du moins, en même temps). De plus, le lien vers professeur est... disons bizarre : un proviseur n'a pas des professeurs.

**Comment by MKertane** [comment]
J'ai ajouté les tables associatives sur le diagramme de classe, qui est accessible sur le readme

S'il y a d'autres ajustements à faire, faites moi signe.
