### ISSUE TITLE
Diagramme UML : utilisation

### ISSUE THREAD

**Issue by droumanet** [MKertane/Asimov-PHP#2]
Ok pour l'héritage de prof referent.

Attention, il n'y a pas d'héritage entre les profs et les cas d'utilisation : il faut utiliser un simple lien (pas une flèche)
Attention, prof Alpha peut saisir des notes dans toutes les matières... créer une vue (maquette) dans laquelle il peut choisir la matière pour les notes, sommes-nous d'accord ?
Le reste est ok 😃

**Comment by MKertane** [comment]
J'ai ajouté le cas d'utilisation "Choisir une matière" pour la version alpha de l'application pour les professeurs. J'ai également changé les flèches en simples liens pour relier les acteurs aux cas d'utilisation.

S'il y a d'autres ajustements à faire, faites moi signe.
